name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run:  dotnet restore RestAPI2/RestAPI2.sln
    - name: Restore dependencies Tests
      run:  dotnet restore CoronaProgram.Tests/CoronaProgram.Tests.csproj
    - name: Build
      run: dotnet build RestAPI2/RestAPI2.sln --no-restore
    - name: Test
      run: dotnet test CoronaProgram.Tests/CoronaProgram.Tests.csproj  --verbosity normal
